# This workflow will install the python package and dependencies, and run tests against a variety of Python versions

name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Install the project
      run: uv sync --all-extras --dev
    - name: Test with pytest
      run: uv run pytest --cov-fail-under 100
    - name: Lint with ruff
      run: uv run ruff check .
    - name: Typecheck with mypy
      run: uv run mypy .
    - name: Build documentation with sphinx
      run: |
        cd docs && uv run sphinx-build -b html source build/html
